//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eexmmaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eexmmaster()
        {
            this.students = new HashSet<student>();
        }
    
        public int id { get; set; }
        public string eegov { get; set; }
        public string eedusection { get; set; }
        public string eschool { get; set; }
        public string elevel { get; set; }
        public string estatus { get; set; }
        public string eyear { get; set; }
        public string eeduppx0 { get; set; }
        public string edocref { get; set; }
        public Nullable<int> epage { get; set; }
        public string erowref { get; set; }
        public Nullable<int> estudentfrom { get; set; }
        public Nullable<int> estudentto { get; set; }
        public string eedulictype { get; set; }
        public string eebook { get; set; }
        public string eeCount { get; set; }
        public Nullable<bool> DocThere { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> IUserDateTime { get; set; }
        public byte[] IUserStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student> students { get; set; }
    }
}
