//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ministryEducationEntities : DbContext
    {
        public ministryEducationEntities()
            : base("name=ministryEducationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<edducyear> edducyears { get; set; }
        public virtual DbSet<eeducon> eeducons { get; set; }
        public virtual DbSet<eeduecert> eeduecerts { get; set; }
        public virtual DbSet<eeduecesub> eeduecesubs { get; set; }
        public virtual DbSet<eeduppx0> eeduppx0 { get; set; }
        public virtual DbSet<eedusection> eedusections { get; set; }
        public virtual DbSet<eexmmaster> eexmmasters { get; set; }
        public virtual DbSet<egov> egovs { get; set; }
        public virtual DbSet<eschool> eschools { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<UserSecuirtyTable> UserSecuirtyTables { get; set; }
        public virtual DbSet<User_Log_Table> User_Log_Table { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<destination> destinations { get; set; }
        public virtual DbSet<request> requests { get; set; }
    }
}
