//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> destination_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> max_grade { get; set; }
        public Nullable<double> total_grade { get; set; }
        public Nullable<double> amount { get; set; }
        public string registrationNumber { get; set; }
        public string transfer_number { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual destination destination { get; set; }
        public virtual student student { get; set; }
    }
}
