//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Log_Table
    {
        public int id { get; set; }
        public string UserLogName { get; set; }
        public Nullable<System.DateTime> Login_System { get; set; }
        public Nullable<System.DateTime> Logout_From_System { get; set; }
    }
}
