//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecuirtyTable
    {
        public int id { get; set; }
        public string IUser_Name { get; set; }
        public string IUser_Login { get; set; }
        public string IUser_Password { get; set; }
        public Nullable<bool> IUser_Enabled { get; set; }
        public Nullable<bool> IUser_New_Form { get; set; }
        public Nullable<bool> IUser_Query_From { get; set; }
        public Nullable<bool> IUser_Notes_Load { get; set; }
        public Nullable<bool> IUser_Print { get; set; }
        public byte[] IUser_C_Date { get; set; }
        public Nullable<int> IUser_Type { get; set; }
    }
}
